/**
 * Agency
 * API of the Agency
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * message for agent communication
 */
export interface ACLMessage { 
    /**
     * sending time
     */
    ts: string;
    /**
     * Denotes the type of the communicative act of the ACL message
     */
    perf: number;
    /**
     * Denotes the identity of the sender of the message
     */
    sender: number;
    /**
     * Denotes the name of the sender agency
     */
    agencys: string;
    /**
     * Denotes the identity of the intended recipients of the message
     */
    receiver: number;
    /**
     * Denotes the name of the receiver agency
     */
    agencyr: string;
    /**
     * This parameter indicates that subsequent messages in this conversation thread are to be directed to the agent named in the reply-to parameter, instead of to the agent named in the sender parameter
     */
    repto?: number;
    /**
     * Denotes the content of the message
     */
    content: string;
    /**
     * Denotes the language in which the content parameter is expressed
     */
    lang?: string;
    /**
     * Denotes the specific encoding of the content language expression
     */
    enc?: string;
    /**
     * Denotes the ontology(s) used to give a meaning to the symbols in the content expression
     */
    ont?: string;
    /**
     * Denotes the interaction protocol that the sending agent is employing with this ACL message
     */
    prot: number;
    /**
     * Introduces an expression which is used to identify the ongoing sequence of communicative acts that together form a conversation
     */
    convid?: number;
    /**
     * Introduces an expression that will be used by the responding agent to identify this message
     */
    repwith?: string;
    /**
     * Denotes an expression that references an earlier action to which this message is a reply
     */
    inrepto?: string;
    /**
     * Denotes a time and/or date expression which indicates the latest time by which the sending agent would like to receive a reply
     */
    repby?: string;
}

