/**
 * Agency
 * API of the Agency
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * holds the address information of an agent
 */
export interface Address { 
    /**
     * name of the agency
     */
    agency: string;
}

