/**
 * Agency
 * API of the Agency
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { LoggerConfig } from './loggerConfig';


/**
 * information about agency
 */
export interface AgencyInfo { 
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * name of agency (hostname of pod given by Kubernetes)
     */
    name: string;
    /**
     * unique ID of agency
     */
    id: number;
    /**
     * unique ID of image group
     */
    imid: number;
    logger: LoggerConfig;
    /**
     * list of all agents in agency
     */
    agents: Array<number>;
    status: Status;
}

