/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BehStats { 
    /**
     * ID of MAS
     */
    masid?: number;
    /**
     * ID of Agent
     */
    agentid?: number;
    /**
     * type of behavior
     */
    behtype?: string;
    /**
     * start time of the behavior
     */
    start?: string;
    /**
     * end time of the behavior
     */
    end?: string;
    /**
     * duration of the behavior
     */
    duration?: number;
}

