/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * communication data
 */
export interface Communication { 
    /**
     * id of other agent
     */
    id: number;
    /**
     * number of messages sent to this agent
     */
    numsent: number;
    /**
     * number of messages recived from this agent
     */
    numrecv: number;
}

