/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * information to be logged
 */
export interface LogMessage { 
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * ID of Agent
     */
    agentid: number;
    /**
     * type of logging
     */
    topic: string;
    /**
     * time at which message was generated
     */
    timestamp: string;
    /**
     * message to be logged
     */
    msg: string;
    /**
     * additional data
     */
    data?: string;
}

