/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * series to be logged
 */
export interface LogSeries { 
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * ID of Agent
     */
    agentid: number;
    /**
     * name of the log series
     */
    name: string;
    /**
     * time at which message was generated
     */
    timestamp: string;
    /**
     * value of the log series
     */
    value: number;
}

