/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * state of agent
 */
export interface State { 
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * ID of agent
     */
    agentid: number;
    /**
     * latest update time
     */
    timestamp: string;
    /**
     * state of agent
     */
    state: string;
}

