/**
 * Logger
 * API of the logger for state saving and logging
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BehStats } from './behStats';


export interface StatsInfo { 
    /**
     * max of the stats
     */
    max?: number;
    /**
     * min of the stats
     */
    min?: number;
    /**
     * count of the stats
     */
    count?: number;
    /**
     * average of the stat
     */
    average?: number;
    /**
     * list for the behavior stats
     */
    list?: Array<BehStats>;
}

