version: "3.7"

services:
  kubestub: 
    container_name: kubestub
    hostname: kubestub
    image: clonemap/clonemap_local:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - 8000:8000
    networks: 
     - clonemap-net
    stop_grace_period: 30s

  ams: 
    image: clonemap/ams:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
      CLONEMAP_STORAGE_TYPE: ${CLONEMAP_STORAGE_TYPE}
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
      CLONEMAP_STUB_HOSTNAME: ${CLONEMAP_STUB_HOSTNAME}
    ports:
     - 30009:9000
    depends_on: 
      - kubestub
    networks: 
      - clonemap-net

  # mqtt: 
  #   image: eclipse-mosquitto
  #   environment: 
  #     CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
  #   tty: true
  #   stdin_open: true
  #   #ports:
  #   #  - 30883:1883
  #   networks: 
  #     - clonemap-net123

networks:
  clonemap-net:
    name: clonemap-net
    attachable: true
