version: "3.7"

services:
  mqtt:
    image: eclipse-mosquitto:1.6.13
    ports:
     - 30883:1883
    depends_on: 
      - kubestub
      - ams
    networks: 
      - clonemap-net

  logger:
    image: clonemap/logger:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
    ports:
      - 30011:11000
    depends_on:
      - kubestub
      - ams
    networks:
      - clonemap-net

  df:
    image: clonemap/df:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
    ports:
      - 30012:12000
    depends_on:
      - kubestub
      - ams
    networks:
      - clonemap-net

  pnp:
    image: clonemap/plugnplay:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
    depends_on:
      - kubestub
      - ams
      - mqtt
    networks:
      - clonemap-net

  fe:
    image: clonemap/frontend:${CLONEMAP_DOCKER_TAG}
    environment:
      CLONEMAP_DEPLOYMENT_TYPE: ${CLONEMAP_DEPLOYMENT_TYPE}
      CLONEMAP_LOG_LEVEL: ${CLONEMAP_LOG_LEVEL}
    ports:
      - 30013:13000
    depends_on:
      - kubestub
      - ams
    networks:
      - clonemap-net
