/**
 * Directory Facilitator
 * API of the DF
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * graph node
 */
export interface Node { 
    /**
     * unique ID of node
     */
    id: number;
    /**
     * list of agents attached to node
     */
    agents?: Array<number>;
}

