/**
 * Directory Facilitator
 * API of the DF
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DF service
 */
export interface Service { 
    /**
     * id of service
     */
    id: number;
    /**
     * id of agent which registered service
     */
    agentid: number;
    /**
     * id of node
     */
    nodeid: number;
    /**
     * id of MAS
     */
    masid: number;
    /**
     * time of creation
     */
    createdat: string;
    /**
     * time of last change
     */
    changedat: string;
    /**
     * description of service
     */
    desc: string;
    /**
     * distance
     */
    dist: number;
}

