/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * contains information about a agent running in a MAS
 */
export interface AgentSpec { 
    /**
     * ID of node
     */
    nodeid: number;
    /**
     * name/description of agent
     */
    name: string;
    /**
     * type of agent (application dependent)
     */
    type?: string;
    /**
     * subtype of agent (application dependent)
     */
    subtype?: string;
    /**
     * custom agent specification
     */
    custom?: string;
}

