/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { AgentInfo } from './agentInfo';
import { LoggerConfig } from './loggerConfig';


/**
 * information about agency
 */
export interface AgencyInfoFull { 
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * ID of agency
     */
    id: number;
    /**
     * name of agency (corresponds to pod name)
     */
    name: string;
    /**
     * id of image group
     */
    imid: number;
    logger: LoggerConfig;
    status: Status;
    /**
     * list of agents in agency
     */
    agents: Array<AgentInfo>;
}

