/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Address } from './address';
import { AgentSpec } from './agentSpec';


/**
 * detailed information about agent
 */
export interface AgentInfo { 
    spec: AgentSpec;
    /**
     * ID of MAS
     */
    masid: number;
    /**
     * ID of agency
     */
    agencyid: number;
    /**
     * unique ID of image group
     */
    imid: number;
    /**
     * unique ID of agent
     */
    id: number;
    address: Address;
    status: Status;
}

