/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgencyInfo } from './agencyInfo';


/**
 * contains informaton about how many agencies are running
 */
export interface Agencies { 
    /**
     * number of running agencies
     */
    counter: number;
    /**
     * agencies
     */
    instances: Array<AgencyInfo>;
}

