/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Node } from './node';
import { Edge } from './edge';


/**
 * stores one mas graph for topological search
 */
export interface Graph { 
    /**
     * list of graph nodes
     */
    node: Array<Node>;
    /**
     * list of graph edges
     */
    edge: Array<Edge>;
}

