/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Agencies } from './agencies';
import { ImageGroupConfig } from './imageGroupConfig';


/**
 * information about an image groups
 */
export interface ImageGroupInfo { 
    config?: ImageGroupConfig;
    /**
     * unique id of image groups
     */
    id?: number;
    agencies?: Agencies;
}

