/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGroupConfig } from './imageGroupConfig';
import { AgentSpec } from './agentSpec';


/**
 * specification of an image groups
 */
export interface ImageGroupSpec { 
    config: ImageGroupConfig;
    /**
     * spec of all agents in image groups
     */
    agents: Array<AgentSpec>;
}

