/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * configuration of image groups
 */
export interface ImageGroupConfig { 
    /**
     * name of the docker image
     */
    image: string;
    /**
     * pull secret to be used for image
     */
    secret: string;
}

