/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGroupInfo } from './imageGroupInfo';


/**
 * contains informaton about all image groups of a mas
 */
export interface ImageGroups { 
    /**
     * number of image groups
     */
    counter: number;
    /**
     * image groups
     */
    instances: Array<ImageGroupInfo>;
}

