/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * contains information about agency
 */
export interface LoggerConfig { 
    /**
     * indicates if logger module is active and/or usable
     */
    active: boolean;
    /**
     * activation of msg log topic
     */
    msg?: boolean;
    /**
     * activation of app log topic
     */
    app?: boolean;
    /**
     * activation of status log topic
     */
    status?: boolean;
    /**
     * activation of debug log topic
     */
    debug?: boolean;
}

