/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MQTTConfig } from './mQTTConfig';
import { DFConfig } from './dFConfig';
import { LoggerConfig } from './loggerConfig';


/**
 * contains information about mas to be started
 */
export interface MASConfig { 
    /**
     * name of MAS
     */
    name: string;
    /**
     * number of agents per agency
     */
    agentsperagency: number;
    mqtt: MQTTConfig;
    df: DFConfig;
    logger: LoggerConfig;
}

