/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { MASConfig } from './mASConfig';


/**
 * short information about MAS
 */
export interface MASInfoShort { 
    config: MASConfig;
    /**
     * unique ID of MAS
     */
    id: number;
    /**
     * number of agents
     */
    numagents: number;
    status: Status;
    /**
     * uptime of MAS
     */
    uptime: string;
}

