/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Graph } from './graph';
import { ImageGroups } from './imageGroups';
import { Agents } from './agents';
import { MASConfig } from './mASConfig';


/**
 * detailed information about MAS
 */
export interface MASInfo { 
    config: MASConfig;
    /**
     * unique ID of MAS
     */
    id: number;
    graph: Graph;
    imagegroups: ImageGroups;
    agents: Agents;
    status: Status;
    /**
     * uptime of MAS
     */
    uptime: string;
}

