/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MASInfo } from './mASInfo';


/**
 * contains informaton about how many MASs are running
 */
export interface MASs { 
    /**
     * number of running mas
     */
    counter: number;
    /**
     * all mas running in clonemap
     */
    instances: Array<MASInfo>;
}

