/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Graph } from './graph';
import { MASConfig } from './mASConfig';
import { ImageGroupSpec } from './imageGroupSpec';


/**
 * contains information about a MAS running in clonemap
 */
export interface MASSpec { 
    config: MASConfig;
    /**
     * image groups in MAS
     */
    imagegroups: Array<ImageGroupSpec>;
    graph: Graph;
}

