/**
 * Agent Management System
 * API of the Agent Management System for user interaction with the MAS and MAS-internal communication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * information about an agent\'s or agency\'s status
 */
export interface Status { 
    /**
     * status code
     */
    code: number;
    /**
     * time of last update
     */
    lastupdate: string;
}

