name: Build & Test

on:
  push:
    branches:
      - develop

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.8
    - name: build ams
      run: cd cmd/ams & CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o ams