name: Build & Test

on:
  push:
    branches:
      - develop

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.8
    - name: build ams
      working-directory: ${{ github.workspace }}/cmd/ams
      run: CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o ams
    - name: test
      working-directory: ${{ github.workspace }}/pkg
      run: |
        go test ./... -coverprofile cover.out
        go tool cover -func cover.out